### ISSUE TITLE
Repository About's License issuse

### ISSUE THREAD

**Issue by 2jun0** [cmd-cv/newtab-pazzletab#1]
I think GitHub can't check the license of this project.
![image](https://user-images.githubusercontent.com/7973448/144419615-18a119d3-28e2-41a0-9a8b-f2d24b4da23a.png)

this repository license is MIT, so I think it should be displayed as below
![image](https://user-images.githubusercontent.com/7973448/144420049-059003fe-7663-4363-a032-c0dc9f4b341b.png)

Is it a setting problem?

**Comment by cmd-cv** [comment]
Wow, Thanks commit issuse, you are right.
I uesd vitesse-webext developed by Anthony Fu, And I modified license. It would be wrong to do that now.
Now, it's been modified back. The vitesse-webext license in scripts/LICENSE.
I'm not sure it's the right thing to do.
